"use strict";

export function numberToText(num) {
  return num?.toLocaleString();
}

export const keywords = [
  "fullmoon",
  "fullmoon real",
  "fullmoon real estate",
  "fullmoon real estate properties",
  "real estate properties",
  "real estate",
  "we buy land",
  "home selling",
  "house selling",
  "selling my home",
  "selling property",
  "selling a home as is",
  "sale my house",
  "selling home",
  "selling land",
  "sell my house",
  "real estate property",
  "selling my property",
  "selling my home as is",
  "buy real estate",
  "buy house",
  "but house as is",
  "buy homes",
  "house for sale",
  "selling your home",
  "real estate services",
  "real estate company",
  "we buy property",
  "selling your property",
  "commercial properties for sale near me",
  "estate agents near me",
  "apartments for sale",
  "new homes for sale near me",
  "land for rent",
  "land buyers",
  "cheap land",
  "vacant land for sale near me",
  "vacant land for sale",
];
